const sanat = {
    colors: [
        { id: 1, suomeksi: 'punainen', englanniksi: 'red' },
        { id: 2, suomeksi: 'sininen', englanniksi: 'blue' },
        { id: 3, suomeksi: 'vihreä', englanniksi: 'green' },
        { id: 4, suomeksi: 'musta', englanniksi: 'black' },
        { id: 5, suomeksi: 'oranssi', englanniksi: 'orange' },
        { id: 6, suomeksi: 'vihreä', englanniksi: 'green' },
        { id: 7, suomeksi: 'valkoinen', englanniksi: 'white' },
        { id: 8, suomeksi: 'harmaa', englanniksi: 'gray' },
        { id: 9, suomeksi: 'vaaleanpunainen', englanniksi: 'pink' },
        { id: 10, suomeksi: 'violetti', englanniksi: 'purple' },
        { id: 12, suomeksi: 'turkoosi', englanniksi: 'turquoise' },
        { id: 896, suomeksi: 'keltainen', englanniksi: 'yellow' },
        { id: 897, suomeksi: 'ruskea', englanniksi: 'brown' },
        { id: 898, suomeksi: 'beige', englanniksi: 'beige' },
    ],
    animals: [
        { id: 13, suomeksi: 'norsu', englanniksi: 'elephant' },
        { id: 14, suomeksi: 'kirahvi', englanniksi: 'giraffe' },
        { id: 15, suomeksi: 'leijona', englanniksi: 'lion' },
        { id: 16, suomeksi: 'tiikeri', englanniksi: 'tiger' },
        { id: 17, suomeksi: 'apina', englanniksi: 'monkey' },
        { id: 18, suomeksi: 'kenguru', englanniksi: 'kangaroo' },
        { id: 19, suomeksi: 'koira', englanniksi: 'dog' },
        { id: 20, suomeksi: 'kissa', englanniksi: 'cat' },
        { id: 21, suomeksi: 'kala', englanniksi: 'fish' },
        { id: 22, suomeksi: 'kani', englanniksi: 'rabbit' },
        { id: 23, suomeksi: 'hamsteri', englanniksi: 'hamster' },
        { id: 24, suomeksi: 'kyyhky', englanniksi: 'pigeon' },
        { id: 25, suomeksi: 'varis', englanniksi: 'crow' },
        { id: 26, suomeksi: 'pöllö', englanniksi: 'owl' },
        { id: 27, suomeksi: 'kotka', englanniksi: 'eagle' },
        { id: 28, suomeksi: 'lehmä', englanniksi: 'cow' },
        { id: 29, suomeksi: 'lammas', englanniksi: 'sheep' },
        { id: 30, suomeksi: 'sika', englanniksi: 'pig' },
        { id: 31, suomeksi: 'hevonen', englanniksi: 'horse' },
        { id: 32, suomeksi: 'kana', englanniksi: 'chicken' },
        { id: 33, suomeksi: 'kukko', englanniksi: 'rooster' },
        { id: 34, suomeksi: 'muurahainen', englanniksi: 'ant' },
        { id: 35, suomeksi: 'kärpänen', englanniksi: 'fly' },
        { id: 36, suomeksi: 'hämähäkki', englanniksi: 'spider' },
        { id: 37, suomeksi: 'mehiläinen', englanniksi: 'bee' },
        { id: 38, suomeksi: 'ampiainen', englanniksi: 'wasp' },
        { id: 39, suomeksi: 'perhonen', englanniksi: 'butterfly' },
        { id: 40, suomeksi: 'sammakko', englanniksi: 'frog' },
        { id: 41, suomeksi: 'undulaatti', englanniksi: 'budgie' },
        { id: 42, suomeksi: 'lisko', englanniksi: 'lizard' },
        { id: 43, suomeksi: 'papukaija', englanniksi: 'parrot' },
        { id: 44, suomeksi: 'kilpikonna', englanniksi: 'tortoise' },
        { id: 45, suomeksi: 'käärme', englanniksi: 'snake' },
        { id: 46, suomeksi: 'gepardi', englanniksi: 'cheetah' },
        { id: 47, suomeksi: 'seepra', englanniksi: 'zebra' },
        { id: 48, suomeksi: 'gorilla', englanniksi: 'gorilla' },
        { id: 49, suomeksi: 'panda', englanniksi: 'panda' },
        { id: 50, suomeksi: 'karhu', englanniksi: 'bear' },
        { id: 51, suomeksi: 'susi', englanniksi: 'wolf' },
        { id: 52, suomeksi: 'kettu', englanniksi: 'fox' },
        { id: 53, suomeksi: 'joutsen', englanniksi: 'swan' },
        { id: 54, suomeksi: 'hirvi', englanniksi: 'elk' },
        { id: 55, suomeksi: 'orava', englanniksi: 'squirrel' },
        { id: 56, suomeksi: 'harakka', englanniksi: 'magpie' },
        { id: 57, suomeksi: 'poro', englanniksi: 'reindeer' },
        { id: 58, suomeksi: 'etana', englanniksi: 'snail' },
        { id: 59, suomeksi: 'lintu', englanniksi: 'bird' },
        { id: 60, suomeksi: 'mato', englanniksi: 'worm' },
        { id: 61, suomeksi: 'peura', englanniksi: 'deer' },
        { id: 62, suomeksi: 'rotta', englanniksi: 'rat' },
        { id: 63, suomeksi: 'hiiri', englanniksi: 'mouse' },
        { id: 64, suomeksi: 'ankka', englanniksi: 'duck' },
        { id: 65, suomeksi: 'pingviini', englanniksi: 'penguin' },
        { id: 66, suomeksi: 'lepakko', englanniksi: 'bat' },
        { id: 67, suomeksi: 'jääkarhu', englanniksi: 'polar bear' },
        { id: 589, suomeksi: 'virtahepo', englanniksi: 'hippo' },
    ],
    groceries: [
        { "id": 592, suomeksi: "virvoitusjuoma", englanniksi: "soda" },
        { "id": 606, suomeksi: "hattara", englanniksi: "candyfloss" },
        { "id": 96, suomeksi: "pekoni", englanniksi: "bacon" },
        { "id": 97, suomeksi: "naudanliha", englanniksi: "beef" },
        { "id": 98, suomeksi: "kana", englanniksi: "chicken" },
        { "id": 99, suomeksi: "kinkku", englanniksi: "ham" },
        { "id": 100, suomeksi: "lammas", englanniksi: "lamb" },
        { "id": 101, suomeksi: "salami", englanniksi: "salami" },
        { "id": 102, suomeksi: "makkarat", englanniksi: "sausages" },
        { "id": 103, suomeksi: "sianliha", englanniksi: "pork" },
        { "id": 104, suomeksi: "kalkkuna", englanniksi: "turkey" },
        { "id": 105, suomeksi: "omena", englanniksi: "apple" },
        { "id": 106, suomeksi: "aprikoosi", englanniksi: "apricot" },
        { "id": 107, suomeksi: "banaani", englanniksi: "banana" },
        { "id": 108, suomeksi: "karhunvatukka", englanniksi: "blackberry" },
        { "id": 109, suomeksi: "mustaviinimarja", englanniksi: "blackcurrant" },
        { "id": 110, suomeksi: "mustikka", englanniksi: "blueberry" },
        { "id": 111, suomeksi: "kirsikka", englanniksi: "cherry" },
        { "id": 112, suomeksi: "kookospähkinä", englanniksi: "coconut" },
        { "id": 113, suomeksi: "viikuna", englanniksi: "fig" },
        { "id": 114, suomeksi: "karviaismarja", englanniksi: "gooseberry" },
        { "id": 115, suomeksi: "viinirypäle", englanniksi: "grape" },
        { "id": 116, suomeksi: "greippi", englanniksi: "grape" },
        { "id": 117, suomeksi: "kiivi", englanniksi: "kiwi fruit" },
        { "id": 118, suomeksi: "sitruuna", englanniksi: "lemon" },
        { "id": 119, suomeksi: "lime", englanniksi: "lime" },
        { "id": 120, suomeksi: "mango", englanniksi: "mango" },
        { "id": 121, suomeksi: "melooni", englanniksi: "melon" },
        { "id": 122, suomeksi: "appelsiini", englanniksi: "orange" },
        { "id": 123, suomeksi: "persikka", englanniksi: "peach" },
        { "id": 124, suomeksi: "päärynä", englanniksi: "pear" },
        { "id": 125, suomeksi: "ananas", englanniksi: "pineapple" },
        { "id": 126, suomeksi: "luumu", englanniksi: "plum" },
        { "id": 127, suomeksi: "granaattiomena", englanniksi: "pomegranate" },
        { "id": 128, suomeksi: "vadelma", englanniksi: "raspberry" },
        { "id": 129, suomeksi: "raparperi", englanniksi: "rhubarb" },
        { "id": 130, suomeksi: "mansikka", englanniksi: "strawberry" },
        { "id": 131, suomeksi: "anjovis", englanniksi: "anchovy" },
        { "id": 132, suomeksi: "turska", englanniksi: "cod" },
        { "id": 133, suomeksi: "silakka", englanniksi: "herring" },
        { "id": 134, suomeksi: "makrilli", englanniksi: "mackerel" },
        { "id": 135, suomeksi: "sardiini", englanniksi: "sardine" },
        { "id": 136, suomeksi: "lohi", englanniksi: "salmon" },
        { "id": 137, suomeksi: "taimen", englanniksi: "trout" },
        { "id": 138, suomeksi: "tonnikala", englanniksi: "tuna" },
        { "id": 139, suomeksi: "artisokka", englanniksi: "artichoke" },
        { "id": 140, suomeksi: "parsa", englanniksi: "asparagus" },
        { "id": 141, suomeksi: "munakoiso", englanniksi: "eggplant" },
        { "id": 142, suomeksi: "avokaado", englanniksi: "avocado" },
        { "id": 143, suomeksi: "punajuuri", englanniksi: "beetroot" },
        { "id": 144, suomeksi: "parsakaali", englanniksi: "broccoli" },
        { "id": 145, suomeksi: "kaali", englanniksi: "cabbage" },
        { "id": 146, suomeksi: "porkkana", englanniksi: "carrot" },
        { "id": 147, suomeksi: "kukkakaali", englanniksi: "cauliflower" },
        { "id": 148, suomeksi: "selleri", englanniksi: "celery" },
        { "id": 149, suomeksi: "kesäkurpitsa", englanniksi: "courgette" },
        { "id": 150, suomeksi: "kurkku", englanniksi: "cucumber" },
        { "id": 151, suomeksi: "valkosipuli", englanniksi: "garlic" },
        { "id": 152, suomeksi: "inkivääri", englanniksi: "ginger" },
        { "id": 153, suomeksi: "purjo", englanniksi: "leek" },
        { "id": 154, suomeksi: "salaatti", englanniksi: "lettuce" },
        { "id": 155, suomeksi: "sieni", englanniksi: "mushroom" },
        { "id": 156, suomeksi: "sipuli", englanniksi: "onion" },
        { "id": 157, suomeksi: "herneet", englanniksi: "peas" },
        { "id": 158, suomeksi: "paprika", englanniksi: "pepper" },
        { "id": 159, suomeksi: "peruna", englanniksi: "potato" },
        { "id": 160, suomeksi: "kurpitsa", englanniksi: "pumpkin" },
        { "id": 161, suomeksi: "retiisi", englanniksi: "radish" },
        { "id": 162, suomeksi: "rucola", englanniksi: "arugula" },
        { "id": 163, suomeksi: "lanttu", englanniksi: "swede" },
        { "id": 164, suomeksi: "bataatti", englanniksi: "sweet potato" },
        { "id": 165, suomeksi: "maissi", englanniksi: "corn" },
        { "id": 166, suomeksi: "tomaatti", englanniksi: "tomato" },
        { "id": 167, suomeksi: "nauris", englanniksi: "turnip" },
        { "id": 168, suomeksi: "pinaatti", englanniksi: "spinach" },
        { "id": 169, suomeksi: "kevätsipuli", englanniksi: "spring onion" },
        { "id": 170, suomeksi: "keitto", englanniksi: "soup" },
        { "id": 171, suomeksi: "ranskanperunat", englanniksi: "chips" },
        { "id": 172, suomeksi: "kalapuikot", englanniksi: "fish fingers" },
        { "id": 173, suomeksi: "pizza", englanniksi: "pizza" },
        { "id": 174, suomeksi: "jäätelö", englanniksi: "ice cream" },
        { "id": 177, suomeksi: "voi", englanniksi: "butter" },
        { "id": 178, suomeksi: "kerma", englanniksi: "cream" },
        { "id": 179, suomeksi: "juusto", englanniksi: "cheese" },
        { "id": 180, suomeksi: "kanamuna", englanniksi: "egg" },
        { "id": 181, suomeksi: "margariini", englanniksi: "margarine" },
        { "id": 182, suomeksi: "maito", englanniksi: "milk" },
        { "id": 183, suomeksi: "jogurtti", englanniksi: "yoghurt" },
        { "id": 184, suomeksi: "patonki", englanniksi: "baguette" },
        { "id": 185, suomeksi: "sämpylä", englanniksi: "bread rolls" },
        { "id": 186, suomeksi: "leipä", englanniksi: "bread" },
        { "id": 187, suomeksi: "kakku", englanniksi: "cake" },
        { "id": 188, suomeksi: "viineri", englanniksi: "Danish pastry" },
        { "id": 192, suomeksi: "sokeri", englanniksi: "sugar" },
        { "id": 193, suomeksi: "tomusokeri", englanniksi: "icing sugar" },
        { "id": 194, suomeksi: "pippuri", englanniksi: "pepper" },
        { "id": 195, suomeksi: "suola", englanniksi: "salt" },
        { "id": 196, suomeksi: "leivos", englanniksi: "pastry" },
        { "id": 197, suomeksi: "hiiva", englanniksi: "yeast" },
        { "id": 198, suomeksi: "rusina", englanniksi: "raisin" },
        { "id": 199, suomeksi: "hunaja", englanniksi: "honey" },
        { "id": 200, suomeksi: "hillo", englanniksi: "jam" },
        { "id": 201, suomeksi: "marmeladi", englanniksi: "marmalade" },
        { "id": 202, suomeksi: "mysli", englanniksi: "muesli" },
        { "id": 203, suomeksi: "puuro", englanniksi: "porridge" },
        { "id": 204, suomeksi: "paahtoleipä", englanniksi: "toast" },
        { "id": 205, suomeksi: "nuudelit", englanniksi: "noodles" },
        { "id": 206, suomeksi: "pasta", englanniksi: "pasta" },
        { "id": 208, suomeksi: "riisi", englanniksi: "rice" },
        { "id": 209, suomeksi: "spagetti", englanniksi: "spaghetti" },
        { "id": 210, suomeksi: "ketsuppi", englanniksi: "ketchup" },
        { "id": 211, suomeksi: "majoneesi", englanniksi: "mayonnaise" },
        { "id": 212, suomeksi: "sinaappi", englanniksi: "mustard" },
        { "id": 214, suomeksi: "etikka", englanniksi: "vinegar" },
        { "id": 215, suomeksi: "keksi", englanniksi: "biscuit" },
        { "id": 216, suomeksi: "suklaa", englanniksi: "chocolate" },
        { "id": 217, suomeksi: "sipsit", englanniksi: "crisps" },
        { "id": 218, suomeksi: "pähkinä", englanniksi: "peanut" },
        { "id": 219, suomeksi: "karkit", englanniksi: "sweets" },
        { "id": 220, suomeksi: "maapähkinät", englanniksi: "walnuts" },
        { "id": 221, suomeksi: "basilika", englanniksi: "basil" },
        { "id": 222, suomeksi: "ruohosipuli", englanniksi: "chives" },
        { "id": 223, suomeksi: "korianteri", englanniksi: "coriander" },
        { "id": 224, suomeksi: "tilli", englanniksi: "dill" },
        { "id": 225, suomeksi: "persilja", englanniksi: "parsley" },
        { "id": 226, suomeksi: "rosmariini", englanniksi: "rosemary" },
        { "id": 227, suomeksi: "salvia", englanniksi: "sage" },
        { "id": 228, suomeksi: "timjami", englanniksi: "thyme" },
        { "id": 230, suomeksi: "kaneli", englanniksi: "cinnamon" },
        { "id": 591, suomeksi: "vesi", englanniksi: "water" },
    ],
    "other things": [
        { "id": 70, suomeksi: "avain", englanniksi: "key" },
        { "id": 71, suomeksi: "raha", englanniksi: "money" },
        { "id": 76, suomeksi: "pensas", englanniksi: "bush" },
        { "id": 80, suomeksi: "rannerengas", englanniksi: "bracelet" },
        { "id": 81, suomeksi: "sormus", englanniksi: "ring" },
        { "id": 82, suomeksi: "kaulakoru", englanniksi: "necklace" },
        { "id": 83, suomeksi: "lämpömittari", englanniksi: "thermometer" },
        { "id": 86, suomeksi: "puu", englanniksi: "tree" },
        { "id": 95, suomeksi: "maa", englanniksi: "earth" },
        { "id": 704, suomeksi: "akvaario", englanniksi: "aquarium" },
        { "id": 705, suomeksi: "sälekaihdin", englanniksi: "blinds" },
        { "id": 469, suomeksi: "valokatkaisin", englanniksi: "lamp switch" },
        { "id": 477, suomeksi: "lämpöpatteri", englanniksi: "radiator" },
        { "id": 487, suomeksi: "ovenkahva", englanniksi: "door handle" },
        { "id": 488, suomeksi: "oven nuppi", englanniksi: "door knob" },
    ],
    "fish and sealife": [
        { "id": 256, suomeksi: "kalmari", englanniksi: "squid" },
        { "id": 257, suomeksi: "hylje", englanniksi: "seal" },
        { "id": 258, suomeksi: "merileijona", englanniksi: "sea lion" },
        { "id": 259, suomeksi: "lohi", englanniksi: "salmon" },
        { "id": 260, suomeksi: "mustekala", englanniksi: "octopus" },
        { "id": 261, suomeksi: "makrilli", englanniksi: "mackerel" },
        { "id": 262, suomeksi: "meduusa", englanniksi: "jellyfish" },
        { "id": 263, suomeksi: "silli", englanniksi: "herring" },
        { "id": 264, suomeksi: "ankerias", englanniksi: "eel" },
        { "id": 265, suomeksi: "delfiini", englanniksi: "dolphin" },
        { "id": 266, suomeksi: "turska", englanniksi: "cod" },
        { "id": 242, suomeksi: "monni", englanniksi: "catfish" },
        { "id": 243, suomeksi: "meritähti", englanniksi: "starfish" },
        { "id": 244, suomeksi: "merisiili", englanniksi: "sea urchin" },
        { "id": 245, suomeksi: "katkarapu", englanniksi: "shrimp" },
        { "id": 246, suomeksi: "(iso)katkarapu", englanniksi: "prawn" },
        { "id": 247, suomeksi: "osteri", englanniksi: "oyster" },
        { "id": 248, suomeksi: "sinisimpukka", englanniksi: "mussel" },
        { "id": 249, suomeksi: "hummeri", englanniksi: "lobster" },
        { "id": 250, suomeksi: "rapu", englanniksi: "crab" },
        { "id": 251, suomeksi: "valas", englanniksi: "whale" },
        { "id": 252, suomeksi: "mursu", englanniksi: "walrus" },
        { "id": 253, suomeksi: "tonnikala", englanniksi: "tuna" },
        { "id": 254, suomeksi: "taimen", englanniksi: "trout" },
        { "id": 255, suomeksi: "hai", englanniksi: "shark" },
    ],
    "kitchen items": [
        { "id": 270, suomeksi: "pöytä", englanniksi: "table" },
        { "id": 271, suomeksi: "tuoli", englanniksi: "chair" },
        { "id": 283, suomeksi: "astianpesukone", englanniksi: "dishwasher" },
        { "id": 287, suomeksi: "liesi", englanniksi: "cooker" },
        { "id": 288, suomeksi: "jääkaappi", englanniksi: "fridge" },
        { "id": 289, suomeksi: "pakastin", englanniksi: "freezer" },
        { "id": 290, suomeksi: "mikroaaltouuni", englanniksi: "microwave" },
        { "id": 291, suomeksi: "leivänpaahdin", englanniksi: "toaster" },
        { "id": 292, suomeksi: "uuni", englanniksi: "oven" },
        { "id": 293, suomeksi: "hella", englanniksi: "stove" },
        { "id": 431, suomeksi: "lavuaari", englanniksi: "sink" },
        { "id": 434, suomeksi: "talouspaperi", englanniksi: "kitchen paper" },
        { "id": 435, suomeksi: "kuivausteline", englanniksi: "draining board" },
        { "id": 436, suomeksi: "kokkikirja", englanniksi: "cookery book" },
        { "id": 437, suomeksi: "muovikelmu", englanniksi: "plastic wrap" },
        { "id": 439, suomeksi: "teekannu", englanniksi: "tea pot" },
        { "id": 440, suomeksi: "sokerikulho", englanniksi: "sugar bowl" },
        { "id": 441, suomeksi: "lautanen", englanniksi: "plate" },
        { "id": 442, suomeksi: "muki", englanniksi: "mug" },
        { "id": 443, suomeksi: "purkki", englanniksi: "jar" },
        { "id": 444, suomeksi: "lasi", englanniksi: "glass" },
        { "id": 445, suomeksi: "kulho", englanniksi: "bowl" },
        { "id": 446, suomeksi: "kuppi", englanniksi: "cup" },
        { "id": 447, suomeksi: "syömäpuikot", englanniksi: "chopsticks" },
        { "id": 448, suomeksi: "lusikka", englanniksi: "spoon" },
        { "id": 449, suomeksi: "haarukka", englanniksi: "fork" },
        { "id": 450, suomeksi: "veitsi", englanniksi: "knife" },
        { "id": 451, suomeksi: "vispilä", englanniksi: "whisk" },
        { "id": 452, suomeksi: "tarjotin", englanniksi: "tray" },
        { "id": 453, suomeksi: "kattila", englanniksi: "kettle" },
        { "id": 454, suomeksi: "kaulin", englanniksi: "rolling pin" },
        { "id": 455, suomeksi: "sekoituskulho", englanniksi: "mixing bowl" },
        { "id": 456, suomeksi: "kauha", englanniksi: "ladle" },
        { "id": 457, suomeksi: "folio", englanniksi: "kitchen foil" },
        { "id": 458, suomeksi: "mehupuristin", englanniksi: "juicer" },
        { "id": 459, suomeksi: "juustoraastin", englanniksi: "cheese grater" },
        { "id": 460, suomeksi: "paistinpannu", englanniksi: "frying pan" },
        { "id": 716, suomeksi: "matto", englanniksi: "carpet" },
        { "id": 461, suomeksi: "siivilä", englanniksi: "colander" },
        { "id": 462, suomeksi: "leikkuulauta", englanniksi: "chopping board" },
        { "id": 463, suomeksi: "pullonavaaja", englanniksi: "bottle opener" },
        { "id": 464, suomeksi: "kahvinkeitin", englanniksi: "coffee maker" },
        { "id": 720, suomeksi: "hylly", englanniksi: "shelf" },
        { "id": 726, suomeksi: "kaappi", englanniksi: "cupboard" },
        { "id": 729, suomeksi: "lamppu", englanniksi: "lamp" },
    ],
    "living room items": [
        { "id": 273, suomeksi: "sohva", englanniksi: "sofa" },
        { "id": 274, suomeksi: "kirjahylly", englanniksi: "bookcase" },
        { "id": 276, suomeksi: "nojatuoli", englanniksi: "armchair" },
        { "id": 72, suomeksi: "televisio", englanniksi: "TV" },
        { "id": 714, suomeksi: "matto", englanniksi: "carpet" },
        { "id": 721, suomeksi: "hylly", englanniksi: "shelf" },
        { "id": 723, suomeksi: "lipasto", englanniksi: "dresser" },
        { "id": 730, suomeksi: "lamppu", englanniksi: "lamp" },
        { "id": 476, suomeksi: "radio", englanniksi: "radio" },
    ],
    "school vocabulary": [
        { "id": 512, suomeksi: "tussi", englanniksi: "marker" },
        { "id": 513, suomeksi: "työkirja", englanniksi: "exercise book" },
        { "id": 514, suomeksi: "oppitunti", englanniksi: "lesson" },
        { "id": 515, suomeksi: "kotitehtävät", englanniksi: "homework" },
        { "id": 516, suomeksi: "koe", englanniksi: "test" },
        { "id": 517, suomeksi: "lukukausi", englanniksi: "term" },
        { "id": 518, suomeksi: "opettaja", englanniksi: "teacher" },
        { "id": 519, suomeksi: "oppilas", englanniksi: "pupil" },
        { "id": 520, suomeksi: "lukeminen", englanniksi: "reading" },
        { "id": 521, suomeksi: "kirjoittaminen", englanniksi: "writing" },
        { "id": 522, suomeksi: "tietokoneluokka", englanniksi: "computer room" },
        { "id": 523, suomeksi: "pukuhuone", englanniksi: "changing room" },
        { "id": 524, suomeksi: "kuntosali", englanniksi: "gymnasium" },
        { "id": 525, suomeksi: "leikkikenttä", englanniksi: "playground" },
        { "id": 526, suomeksi: "kirjasto", englanniksi: "library" },
        { "id": 527, suomeksi: "luentosali", englanniksi: "lecture hall" },
        { "id": 272, suomeksi: "työpöytä", englanniksi: "desk" },
        { "id": 528, suomeksi: "lokero", englanniksi: "locker" },
        { "id": 529, suomeksi: "liikuntasali", englanniksi: "sports hall" },
        { "id": 530, suomeksi: "lukio", englanniksi: "college" },
        { "id": 531, suomeksi: "peruskoulu", englanniksi: "primary school" },
        { "id": 532, suomeksi: "yläaste", englanniksi: "secondary school" },
        { "id": 533, suomeksi: "yksityiskoulu", englanniksi: "private school" },
        { "id": 534, suomeksi: "sisäoppilaitos", englanniksi: "boarding school" },
        { "id": 535, suomeksi: "ammattikoulu", englanniksi: "vocational school" },
        { "id": 536, suomeksi: "taidekoulu", englanniksi: "art school" },
        { "id": 537, suomeksi: "yliopisto", englanniksi: "university" },
        { "id": 538, suomeksi: "lyijykynä", englanniksi: "pencil" },
        { "id": 539, suomeksi: "opiskelija", englanniksi: "student" },
        { "id": 540, suomeksi: "kurssi", englanniksi: "course" },
        { "id": 541, suomeksi: "aine", englanniksi: "subject" },
        { "id": 542, suomeksi: "arvosana", englanniksi: "grade" },
        { "id": 543, suomeksi: "laskin", englanniksi: "calculator" },
        { "id": 544, suomeksi: "oppikirja", englanniksi: "textbook" },
        { "id": 545, suomeksi: "kysymys", englanniksi: "question" },
        { "id": 546, suomeksi: "vastaus", englanniksi: "answer" },
        { "id": 547, suomeksi: "virhe", englanniksi: "mistake" },
        { "id": 548, suomeksi: "oikein", englanniksi: "correct" },
        { "id": 549, suomeksi: "väärin", englanniksi: "wrong" },
        { "id": 294, suomeksi: "kannettava tietokone", englanniksi: "laptop" },
        { "id": 338, suomeksi: "reppu", englanniksi: "backpack" },
        { "id": 502, suomeksi: "koulu", englanniksi: "school" },
        { "id": 503, suomeksi: "kynä", englanniksi: "pen" },
        { "id": 504, suomeksi: "viivotin", englanniksi: "ruler" },
        { "id": 505, suomeksi: "penaali", englanniksi: "pencil case" },
        { "id": 506, suomeksi: "pyyhekumi", englanniksi: "rubber" },
        { "id": 507, suomeksi: "vihko", englanniksi: "notebook" },
        { "id": 508, suomeksi: "luokka", englanniksi: "classroom" },
        { "id": 509, suomeksi: "pulpetti", englanniksi: "desk" },
        { "id": 510, suomeksi: "liitutaulu", englanniksi: "blackboard" },
        { "id": 511, suomeksi: "liitu", englanniksi: "chalk" },
    ],
    "clothing and accessories": [
        { "id": 318, suomeksi: "uimapuku", englanniksi: "swimsuit" },
        { "id": 319, suomeksi: "huivi", englanniksi: "scarf" },
        { "id": 320, suomeksi: "yöpaita", englanniksi: "nightdress" },
        { "id": 321, suomeksi: "neulepusero", englanniksi: "jumper" },
        { "id": 322, suomeksi: "takki", englanniksi: "jacket" },
        { "id": 323, suomeksi: "mekko", englanniksi: "dress" },
        { "id": 324, suomeksi: "hansikkaat", englanniksi: "gloves" },
        { "id": 325, suomeksi: "lapaset", englanniksi: "mittens" },
        { "id": 326, suomeksi: "yöpuku", englanniksi: "pyjamas" },
        { "id": 327, suomeksi: "alushousut", englanniksi: "underpants" },
        { "id": 328, suomeksi: "uimahousut", englanniksi: "swimming trunks" },
        { "id": 329, suomeksi: "jalkapallokengät", englanniksi: "football boots" },
        { "id": 330, suomeksi: "alusvaatteet", englanniksi: "underwear" },
        { "id": 331, suomeksi: "collegehousut", englanniksi: "sweatpants" },
        { "id": 332, suomeksi: "collegepusero", englanniksi: "sweatshirt" },
        { "id": 333, suomeksi: "farkut", englanniksi: "jeans" },
        { "id": 334, suomeksi: "hame", englanniksi: "skirt" },
        { "id": 590, suomeksi: "pipo", englanniksi: "beanie" },
        { "id": 335, suomeksi: "hattu", englanniksi: "hat" },
        { "id": 336, suomeksi: "housut", englanniksi: "trousers" },
        { "id": 337, suomeksi: "huppari", englanniksi: "hoodie" },
        { "id": 339, suomeksi: "kumisaappaat", englanniksi: "wellies" },
        { "id": 340, suomeksi: "kypärä", englanniksi: "helmet" },
        { "id": 341, suomeksi: "legginsit", englanniksi: "leggings" },
        { "id": 342, suomeksi: "lenkkarit", englanniksi: "sneakers" },
        { "id": 343, suomeksi: "lippis", englanniksi: "cap" },
        { "id": 344, suomeksi: "luistimet", englanniksi: "skates" },
        { "id": 345, suomeksi: "rullaluistimet", englanniksi: "rollerblades" },
        { "id": 346, suomeksi: "saappaat", englanniksi: "boots" },
        { "id": 347, suomeksi: "silmälasit", englanniksi: "glasses" },
        { "id": 348, suomeksi: "sukat", englanniksi: "socks" },
        { "id": 349, suomeksi: "shortsit", englanniksi: "shorts" },
        { "id": 350, suomeksi: "toppi", englanniksi: "top" },
        { "id": 351, suomeksi: "t-paita", englanniksi: "t-shirt" },
        { "id": 352, suomeksi: "varvastossut", englanniksi: "flip-flops" },
        { "id": 353, suomeksi: "villapaita", englanniksi: "sweater" },
    ],
    "bathroom items": [
        { "id": 277, suomeksi: "suihku", englanniksi: "shower" },
        { "id": 278, suomeksi: "kylpyamme", englanniksi: "bathtub" },
        { "id": 279, suomeksi: "lavuaari", englanniksi: "sink" },
        { "id": 280, suomeksi: "peili", englanniksi: "mirror" },
        { "id": 282, suomeksi: "hana", englanniksi: "tap" },
        { "id": 284, suomeksi: "pyykinpesukone", englanniksi: "washing machine" },
        { "id": 285, suomeksi: "hiustenkuivaaja", englanniksi: "hair dryer" },
        { "id": 77, suomeksi: "hammastahna", englanniksi: "toothpaste" },
        { "id": 78, suomeksi: "hammasharja", englanniksi: "toothbrush" },
        { "id": 595, suomeksi: "kampa", englanniksi: "comb" },
        { "id": 609, suomeksi: "kynsilakka", englanniksi: "nail polish" },
        { "id": 610, suomeksi: "shampoo", englanniksi: "shampoo" },
        { "id": 611, suomeksi: "voide", englanniksi: "lotion" },
        { "id": 612, suomeksi: "hoitoaine", englanniksi: "conditioner" },
        { "id": 613, suomeksi: "deodorantti", englanniksi: "deodorant" },
        { "id": 614, suomeksi: "hiusgeeli", englanniksi: "hair gel" },
        { "id": 615, suomeksi: "saippua", englanniksi: "soap" },
        { "id": 616, suomeksi: "huulipuna", englanniksi: "lipstick" },
        { "id": 617, suomeksi: "huulirasva", englanniksi: "lip balm" },
        { "id": 632, suomeksi: "pyyhe", englanniksi: "towel" },
        { "id": 432, suomeksi: "hylly", englanniksi: "shelf" },
        { "id": 433, suomeksi: "tulppa", englanniksi: "plug" },
        { "id": 438, suomeksi: "roskakori", englanniksi: "bin" },
        { "id": 712, suomeksi: "matto", englanniksi: "carpet" },
        { "id": 724, suomeksi: "kaappi", englanniksi: "cupboard" },
        { "id": 727, suomeksi: "lamppu", englanniksi: "lamp" },
    ],
    vehicles: [
        { "id": 644, suomeksi: "lautta", englanniksi: "ferry" },
        { "id": 645, suomeksi: "asuntoauto", englanniksi: "campervan" },
        { "id": 646, suomeksi: "bussi", englanniksi: "bus" },
        { "id": 647, suomeksi: "auto", englanniksi: "car" },
        { "id": 648, suomeksi: "asuntovaunu", englanniksi: "caravan" },
        { "id": 649, suomeksi: "rekka", englanniksi: "truck" },
        { "id": 650, suomeksi: "mopo", englanniksi: "moped" },
        { "id": 651, suomeksi: "moottoripyörä", englanniksi: "motorcycle" },
        { "id": 652, suomeksi: "skootteri", englanniksi: "scooter" },
        { "id": 653, suomeksi: "taksi", englanniksi: "taxi" },
        { "id": 654, suomeksi: "traktori", englanniksi: "tractor" },
        { "id": 655, suomeksi: "kuorma-auto", englanniksi: "lorry" },
        { "id": 656, suomeksi: "pakettiauto", englanniksi: "van" },
        { "id": 657, suomeksi: "vene", englanniksi: "boat" },
        { "id": 658, suomeksi: "laiva", englanniksi: "ship" },
        { "id": 659, suomeksi: "polkupyörä", englanniksi: "bicycle" },
        { "id": 703, suomeksi: "kaivinkone", englanniksi: "excavator" },
    ],
    "human body": [
        { "id": 660, suomeksi: "parta", englanniksi: "beard" },
        { "id": 661, suomeksi: "poski", englanniksi: "cheek" },
        { "id": 662, suomeksi: "leuka", englanniksi: "chin" },
        { "id": 663, suomeksi: "hiukset", englanniksi: "hair" },
        { "id": 664, suomeksi: "pää", englanniksi: "head" },
        { "id": 665, suomeksi: "korva", englanniksi: "ear" },
        { "id": 666, suomeksi: "silmä", englanniksi: "eye" },
        { "id": 667, suomeksi: "kulmakarva", englanniksi: "eyebrow" },
        { "id": 668, suomeksi: "ripsi", englanniksi: "eyelash" },
        { "id": 669, suomeksi: "silmäluomi", englanniksi: "eyelid" },
        { "id": 670, suomeksi: "otsa", englanniksi: "forehead" },
        { "id": 671, suomeksi: "pisamat", englanniksi: "freckles" },
        { "id": 672, suomeksi: "huulet", englanniksi: "lips" },
        { "id": 673, suomeksi: "viikset", englanniksi: "mustache" },
        { "id": 674, suomeksi: "suu", englanniksi: "mouth" },
        { "id": 675, suomeksi: "nenä", englanniksi: "nose" },
        { "id": 676, suomeksi: "kieli", englanniksi: "tongue" },
        { "id": 677, suomeksi: "hammas", englanniksi: "tooth" },
        { "id": 678, suomeksi: "käsivarsi", englanniksi: "arm" },
        { "id": 679, suomeksi: "kainalo", englanniksi: "armpit" },
        { "id": 680, suomeksi: "selkä", englanniksi: "back" },
        { "id": 681, suomeksi: "rintakehä", englanniksi: "chest" },
        { "id": 682, suomeksi: "kyynärpää", englanniksi: "elbow" },
        { "id": 683, suomeksi: "käsi", englanniksi: "hand" },
        { "id": 684, suomeksi: "kynsi", englanniksi: "nail" },
        { "id": 685, suomeksi: "kyynärvarsi", englanniksi: "forearm" },
        { "id": 686, suomeksi: "sormi", englanniksi: "finger" },
        { "id": 687, suomeksi: "napa", englanniksi: "belly button" },
        { "id": 688, suomeksi: "niska", englanniksi: "neck" },
        { "id": 689, suomeksi: "olkapää", englanniksi: "shoulder" },
        { "id": 690, suomeksi: "kurkku", englanniksi: "throat" },
        { "id": 691, suomeksi: "vyötärö", englanniksi: "waist" },
        { "id": 692, suomeksi: "ranne", englanniksi: "wrist" },
        { "id": 693, suomeksi: "nilkka", englanniksi: "ankle" },
        { "id": 694, suomeksi: "vatsa", englanniksi: "stomach" },
        { "id": 695, suomeksi: "sääri", englanniksi: "shin" },
        { "id": 696, suomeksi: "jalkaterä", englanniksi: "foot" },
        { "id": 697, suomeksi: "kantapää", englanniksi: "heel" },
        { "id": 698, suomeksi: "lantio", englanniksi: "hip" },
        { "id": 699, suomeksi: "polvi", englanniksi: "knee" },
        { "id": 700, suomeksi: "jalka", englanniksi: "foot" },
        { "id": 701, suomeksi: "reisi", englanniksi: "thigh" },
        { "id": 702, suomeksi: "varvas", englanniksi: "toe" },
    ],
    countries: [
        { "id": 768, suomeksi: "Yhdysvallat", englanniksi: "United States" },
        { "id": 769, suomeksi: "Jamaika", englanniksi: "Jamaica" },
        { "id": 770, suomeksi: "Argentiina", englanniksi: "Argentina" },
        { "id": 771, suomeksi: "Brasilia", englanniksi: "Brazil" },
        { "id": 772, suomeksi: "Israel", englanniksi: "Israel" },
        { "id": 773, suomeksi: "Kolumbia", englanniksi: "Colombia" },
        { "id": 774, suomeksi: "Irak", englanniksi: "Iraq" },
        { "id": 775, suomeksi: "Iran", englanniksi: "Iran" },
        { "id": 776, suomeksi: "Saudi-Arabia", englanniksi: "Saudi Arabia" },
        { "id": 777, suomeksi: "Syyria", englanniksi: "Syria" },
        { "id": 778, suomeksi: "Turkki", englanniksi: "Turkey" },
        { "id": 779, suomeksi: "Afrikka", englanniksi: "Africa" },
        { "id": 780, suomeksi: "Madagaskar", englanniksi: "Madagascar" },
        { "id": 781, suomeksi: "Kenia", englanniksi: "Kenya" },
        { "id": 782, suomeksi: "Egypti", englanniksi: "Egypt" },
        { "id": 783, suomeksi: "Algeria", englanniksi: "Algeria" },
        { "id": 784, suomeksi: "Vietnam", englanniksi: "Vietnam" },
        { "id": 785, suomeksi: "Australia", englanniksi: "Australia" },
        { "id": 786, suomeksi: "Uusi-Seelanti", englanniksi: "New Zealand" },
        { "id": 787, suomeksi: "Thaimaa", englanniksi: "Thailand" },
        { "id": 788, suomeksi: "Filippiinit", englanniksi: "Philippines" },
        { "id": 789, suomeksi: "Malesia", englanniksi: "Malaysia" },
        { "id": 790, suomeksi: "Indonesia", englanniksi: "Indonesia" },
        { "id": 791, suomeksi: "Taiwan", englanniksi: "Taiwan" },
        { "id": 792, suomeksi: "Etelä-Korea", englanniksi: "South Korea" },
        { "id": 793, suomeksi: "Pohjois-Korea", englanniksi: "North Korea" },
        { "id": 794, suomeksi: "Mongolia", englanniksi: "Mongolia" },
        { "id": 795, suomeksi: "Japani", englanniksi: "Japan" },
        { "id": 796, suomeksi: "Kiina", englanniksi: "China" },
        { "id": 797, suomeksi: "Kazakstan", englanniksi: "Kazakhstan" },
        { "id": 798, suomeksi: "Intia", englanniksi: "India" },
        { "id": 799, suomeksi: "Afganistan", englanniksi: "Afghanistan" },
        { "id": 731, suomeksi: "Tanska", englanniksi: "Denmark" },
        { "id": 732, suomeksi: "Englanti", englanniksi: "England" },
        { "id": 733, suomeksi: "Viro", englanniksi: "Estonia" },
        { "id": 734, suomeksi: "Suomi", englanniksi: "Finland" },
        { "id": 735, suomeksi: "Islanti", englanniksi: "Iceland" },
        { "id": 736, suomeksi: "Irlanti", englanniksi: "Ireland" },
        { "id": 737, suomeksi: "Latvia", englanniksi: "Latvia" },
        { "id": 738, suomeksi: "Liettua", englanniksi: "Lithuania" },
        { "id": 739, suomeksi: "Norja", englanniksi: "Norway" },
        { "id": 740, suomeksi: "Skotlanti", englanniksi: "Scotland" },
        { "id": 741, suomeksi: "Ruotsi", englanniksi: "Sweden" },
        { "id": 742, suomeksi: "Yhdistynyt kuningaskunta", englanniksi: "United Kingdom" },
        { "id": 743, suomeksi: "Wales", englanniksi: "Wales" },
        { "id": 744, suomeksi: "Itävalta", englanniksi: "Austria" },
        { "id": 745, suomeksi: "Belgia", englanniksi: "Belgium" },
        { "id": 746, suomeksi: "Ranska", englanniksi: "France" },
        { "id": 747, suomeksi: "Saksa", englanniksi: "Germany" },
        { "id": 748, suomeksi: "Alankomaat", englanniksi: "Netherlands" },
        { "id": 749, suomeksi: "Sveitsi", englanniksi: "Switzerland" },
        { "id": 750, suomeksi: "Albania", englanniksi: "Albania" },
        { "id": 751, suomeksi: "Kroatia", englanniksi: "Croatia" },
        { "id": 752, suomeksi: "Kypros", englanniksi: "Cyprus" },
        { "id": 753, suomeksi: "Kreikka", englanniksi: "Greece" },
        { "id": 754, suomeksi: "Italia", englanniksi: "Italy" },
        { "id": 755, suomeksi: "Portugali", englanniksi: "Portugal" },
        { "id": 756, suomeksi: "Serbia", englanniksi: "Serbia" },
        { "id": 757, suomeksi: "Slovenia", englanniksi: "Slovenia" },
        { "id": 758, suomeksi: "Espanja", englanniksi: "Spain" },
        { "id": 759, suomeksi: "Bulgaria", englanniksi: "Bulgaria" },
        { "id": 760, suomeksi: "Tsekki", englanniksi: "Czech Republic" },
        { "id": 761, suomeksi: "Unkari", englanniksi: "Hungary" },
        { "id": 762, suomeksi: "Puola", englanniksi: "Poland" },
        { "id": 763, suomeksi: "Romania", englanniksi: "Romania" },
        { "id": 764, suomeksi: "Venäjä", englanniksi: "Russia" },
        { "id": 765, suomeksi: "Slovakia", englanniksi: "Slovakia" },
        { "id": 766, suomeksi: "Ukraina", englanniksi: "Ukraine" },
        { "id": 767, suomeksi: "Kanada", englanniksi: "Canada" },
    ],
    languages: [
        { "id": 800, suomeksi: "slovakian", englanniksi: "Slovak" },
        { "id": 801, suomeksi: "venäjän", englanniksi: "Russian" },
        { "id": 802, suomeksi: "romanian", englanniksi: "Romanian" },
        { "id": 803, suomeksi: "puolan", englanniksi: "Polish" },
        { "id": 804, suomeksi: "unkarin", englanniksi: "Hungarian" },
        { "id": 805, suomeksi: "tsekkin", englanniksi: "Czech" },
        { "id": 806, suomeksi: "bulgaria", englanniksi: "Bulgarian" },
        { "id": 807, suomeksi: "espanjan", englanniksi: "Spanish" },
        { "id": 808, suomeksi: "slovenian", englanniksi: "Slovenian" },
        { "id": 809, suomeksi: "serbian", englanniksi: "Serbian" },
        { "id": 810, suomeksi: "portugalin", englanniksi: "Portuguese" },
        { "id": 811, suomeksi: "italian", englanniksi: "Italian" },
        { "id": 812, suomeksi: "kreikan", englanniksi: "Greek" },
        { "id": 813, suomeksi: "kroatian", englanniksi: "Croatian" },
        { "id": 814, suomeksi: "alabanian", englanniksi: "Albanian" },
        { "id": 815, suomeksi: "hollannin", englanniksi: "Dutch" },
        { "id": 816, suomeksi: "ranskan", englanniksi: "French" },
        { "id": 817, suomeksi: "saksan", englanniksi: "German" },
        { "id": 818, suomeksi: "walesin", englanniksi: "Welsh" },
        { "id": 819, suomeksi: "ruotsin", englanniksi: "Swedish" },
        { "id": 820, suomeksi: "skotlannin", englanniksi: "Scottish Gaelic" },
        { "id": 821, suomeksi: "norjan", englanniksi: "Norwegian" },
        { "id": 822, suomeksi: "liettuan", englanniksi: "Lithuanian" },
        { "id": 823, suomeksi: "latvian", englanniksi: "Latvian" },
        { "id": 824, suomeksi: "irlannin", englanniksi: "Irish" },
        { "id": 825, suomeksi: "islannin", englanniksi: "Icelandic" },
        { "id": 826, suomeksi: "englannin", englanniksi: "English" },
        { "id": 827, suomeksi: "tanskan", englanniksi: "Danish" },
        { "id": 828, suomeksi: "viron", englanniksi: "Estonian" },
        { "id": 829, suomeksi: "suomen", englanniksi: "Finnish" },
        { "id": 830, suomeksi: "ukrainan", englanniksi: "Ukrainian" },
        { "id": 831, suomeksi: "iranin", englanniksi: "Persian" },
        { "id": 832, suomeksi: "arabian", englanniksi: "Arabic" },
        { "id": 833, suomeksi: "turkin", englanniksi: "Turkish" },
        { "id": 834, suomeksi: "madagaskarin", englanniksi: "Malagasy" },
        { "id": 835, suomeksi: "kenian", englanniksi: "Swahili" },
        { "id": 836, suomeksi: "vietnamin", englanniksi: "Vietnamese" },
        { "id": 837, suomeksi: "thaimaan", englanniksi: "Thai" },
        { "id": 838, suomeksi: "filippiinin", englanniksi: "Filipino" },
        { "id": 839, suomeksi: "malesian", englanniksi: "Malay" },
        { "id": 840, suomeksi: "indonesian", englanniksi: "Indonesian" },
        { "id": 841, suomeksi: "korean", englanniksi: "Korean" },
        { "id": 842, suomeksi: "mongolian", englanniksi: "Mongolian" },
        { "id": 843, suomeksi: "japanin", englanniksi: "Japanese" },
        { "id": 844, suomeksi: "kiinan", englanniksi: "Chinese" },
        { "id": 845, suomeksi: "kazakstanin", englanniksi: "Kazakh" },
        { "id": 846, suomeksi: "intian", englanniksi: "Hindi" },
        { "id": 847, suomeksi: "afganistanin", englanniksi: "Pashto" },
    ],
    "bedroom items": [
        { "id": 269, suomeksi: "sänky", englanniksi: "bed" },
        { "id": 281, suomeksi: "vaatekaappi", englanniksi: "wardrobe" },
        { "id": 707, suomeksi: "patja", englanniksi: "mattress" },
        { "id": 708, suomeksi: "tyyny", englanniksi: "pillow" },
        { "id": 711, suomeksi: "lakana", englanniksi: "sheet" },
        { "id": 713, suomeksi: "matto", englanniksi: "carpet" },
        { "id": 717, suomeksi: "hylly", englanniksi: "shelf" },
        { "id": 722, suomeksi: "lipasto", englanniksi: "dresser" },
        { "id": 725, suomeksi: "kaappi", englanniksi: "cupboard" },
        { "id": 728, suomeksi: "lamppu", englanniksi: "lamp" },
        { "id": 484, suomeksi: "herätyskello", englanniksi: "alarm clock" },
    ],
    "musical instruments": [
        { "id": 490, suomeksi: "piano", englanniksi: "piano" },
        { "id": 491, suomeksi: "banjo", englanniksi: "banjo" },
        { "id": 492, suomeksi: "sello", englanniksi: "cello" },
        { "id": 493, suomeksi: "kitara", englanniksi: "guitar" },
        { "id": 494, suomeksi: "viulu", englanniksi: "violin" },
        { "id": 495, suomeksi: "trumpetti", englanniksi: "trumpet" },
        { "id": 496, suomeksi: "tuuba", englanniksi: "tuba" },
        { "id": 497, suomeksi: "säkkipilli", englanniksi: "bagpipes" },
        { "id": 498, suomeksi: "klarinetti", englanniksi: "clarinet" },
        { "id": 499, suomeksi: "huilu", englanniksi: "flute" },
        { "id": 500, suomeksi: "rummut", englanniksi: "drums" },
        { "id": 501, suomeksi: "rumpusetti", englanniksi: "drum set" },
    ],
    "decoration items": [
        { "id": 268, suomeksi: "lamppu", englanniksi: "lamp" },
        { "id": 275, suomeksi: "matto", englanniksi: "carpet" },
        { "id": 593, suomeksi: "kalenteri", englanniksi: "calendar" },
        { "id": 84, suomeksi: "henkari", englanniksi: "hanger" },
        { "id": 85, suomeksi: "maalaus", englanniksi: "painting" },
        { "id": 92, suomeksi: "maljakko", englanniksi: "vase" },
        { "id": 93, suomeksi: "kasvi", englanniksi: "plant" },
        { "id": 94, suomeksi: "kynttilä", englanniksi: "candle" },
        { "id": 430, suomeksi: "pöytäliina", englanniksi: "tablecloth" },
        { "id": 706, suomeksi: "verhot", englanniksi: "curtains" },
        { "id": 709, suomeksi: "tyyny", englanniksi: "pillow" },
        { "id": 710, suomeksi: "tyynyliina", englanniksi: "pillow case" },
        { "id": 718, suomeksi: "hylly", englanniksi: "shelf" },
        { "id": 468, suomeksi: "juliste", englanniksi: "poster" },
        { "id": 470, suomeksi: "kuva", englanniksi: "picture" },
        { "id": 472, suomeksi: "lampunvarjostin", englanniksi: "lampshade" },
        { "id": 474, suomeksi: "huonekasvi", englanniksi: "houseplant" },
        { "id": 475, suomeksi: "levysoitin", englanniksi: "record player" },
        { "id": 489, suomeksi: "ovimatto", englanniksi: "doormat" },
    ],
    places: [
        { "id": 550, suomeksi: "talo", englanniksi: "house" },
        { "id": 551, suomeksi: "taidegalleria", englanniksi: "art gallery" },
        { "id": 552, suomeksi: "pankki", englanniksi: "bank" },
        { "id": 553, suomeksi: "baari", englanniksi: "bar" },
        { "id": 554, suomeksi: "kahvila", englanniksi: "cafe" },
        { "id": 555, suomeksi: "katedraali", englanniksi: "cathedral" },
        { "id": 556, suomeksi: "kirkko", englanniksi: "church" },
        { "id": 557, suomeksi: "elokuvateatteri", englanniksi: "cinema" },
        { "id": 558, suomeksi: "konserttisali", englanniksi: "concert hall" },
        { "id": 559, suomeksi: "hammaslääkäri", englanniksi: "dentists" },
        { "id": 560, suomeksi: "paloasema", englanniksi: "fire station" },
        { "id": 561, suomeksi: "autotalli", englanniksi: "garage" },
        { "id": 562, suomeksi: "kuntosali", englanniksi: "gym" },
        { "id": 563, suomeksi: "terveyskeskus", englanniksi: "health center" },
        { "id": 564, suomeksi: "sairaala", englanniksi: "hospital" },
        { "id": 565, suomeksi: "hotelli", englanniksi: "hotel" },
        { "id": 566, suomeksi: "urheilukeskus", englanniksi: "sports center" },
        { "id": 567, suomeksi: "kirjasto", englanniksi: "library" },
        { "id": 568, suomeksi: "museo", englanniksi: "museum" },
        { "id": 569, suomeksi: "huoltoasema", englanniksi: "petrol station" },
        { "id": 570, suomeksi: "poliisiasema", englanniksi: "police station" },
        { "id": 571, suomeksi: "posti", englanniksi: "post office" },
        { "id": 572, suomeksi: "ravintola", englanniksi: "restaurant" },
        { "id": 573, suomeksi: "koulu", englanniksi: "school" },
        { "id": 574, suomeksi: "ostoskeskus", englanniksi: "shopping center" },
        { "id": 575, suomeksi: "pilvenpiirtäjä", englanniksi: "skyscraper" },
        { "id": 576, suomeksi: "uimahalli", englanniksi: "swimming hall" },
        { "id": 577, suomeksi: "teatteri", englanniksi: "theater" },
        { "id": 578, suomeksi: "kaupungintalo", englanniksi: "town hall" },
        { "id": 579, suomeksi: "eläinlääkäri", englanniksi: "vet" },
        { "id": 68, suomeksi: "kesämökki", englanniksi: "summer cottage" },
        { "id": 580, suomeksi: "keilahalli", englanniksi: "bowling alley" },
        { "id": 69, suomeksi: "talo", englanniksi: "house" },
        { "id": 581, suomeksi: "bussiasema", englanniksi: "bus station" },
        { "id": 582, suomeksi: "hautausmaa", englanniksi: "cemetery" },
        { "id": 583, suomeksi: "tori", englanniksi: "marketplace" },
        { "id": 584, suomeksi: "puisto", englanniksi: "park" },
        { "id": 585, suomeksi: "skeittipuisto", englanniksi: "skate park" },
        { "id": 586, suomeksi: "stadioni", englanniksi: "stadium" },
        { "id": 587, suomeksi: "rautatieasema", englanniksi: "train station" },
        { "id": 588, suomeksi: "eläintarha", englanniksi: "zoo" },
        { "id": 596, suomeksi: "ranta", englanniksi: "beach" },
    ],
    months: [
        { "id": 306, suomeksi: "tammikuu", englanniksi: "January" },
        { "id": 307, suomeksi: "helmikuu", englanniksi: "February" },
        { "id": 308, suomeksi: "maaliskuu", englanniksi: "March" },
        { "id": 309, suomeksi: "huhtikuu", englanniksi: "April" },
        { "id": 310, suomeksi: "toukokuu", englanniksi: "May" },
        { "id": 311, suomeksi: "kesäkuu", englanniksi: "June" },
        { "id": 312, suomeksi: "heinäkuu", englanniksi: "July" },
        { "id": 313, suomeksi: "elokuu", englanniksi: "August" },
        { "id": 314, suomeksi: "syyskuu", englanniksi: "September" },
        { "id": 315, suomeksi: "lokakuu", englanniksi: "October" },
        { "id": 316, suomeksi: "marraskuu", englanniksi: "November" },
        { "id": 317, suomeksi: "joulukuu", englanniksi: "December" },
    ],
    seasons: [
        { "id": 302, suomeksi: "kevät", englanniksi: "spring" },
        { "id": 303, suomeksi: "kesä", englanniksi: "summer" },
        { "id": 304, suomeksi: "syksy", englanniksi: "autumn" },
        { "id": 305, suomeksi: "talvi", englanniksi: "winter" },
    ],
    "days of the week": [
        { "id": 295, suomeksi: "maanantai", englanniksi: "Monday" },
        { "id": 296, suomeksi: "tiistai", englanniksi: "Tuesday" },
        { "id": 297, suomeksi: "keskiviikko", englanniksi: "Wednesday" },
        { "id": 298, suomeksi: "torstai", englanniksi: "Thursday" },
        { "id": 299, suomeksi: "perjantai", englanniksi: "Friday" },
        { "id": 300, suomeksi: "lauantai", englanniksi: "Saturday" },
        { "id": 301, suomeksi: "sunnuntai", englanniksi: "Sunday" },
    ],
    "the rooms": [
        { "id": 354, suomeksi: "makuuhuone", englanniksi: "bedroom" },
        { "id": 355, suomeksi: "olohuone", englanniksi: "living room" },
        { "id": 356, suomeksi: "kylpyhuone", englanniksi: "bathroom" },
        { "id": 357, suomeksi: "vessa", englanniksi: "toilet" },
        { "id": 358, suomeksi: "keittiö", englanniksi: "kitchen" },
        { "id": 359, suomeksi: "eteinen", englanniksi: "hall" },
        { "id": 360, suomeksi: "komero", englanniksi: "closet" },
        { "id": 361, suomeksi: "autotalli", englanniksi: "garage" },
        { "id": 362, suomeksi: "käytävä", englanniksi: "hall" },
    ],
    numbers: [
        { "id": 363, suomeksi: "yksi", englanniksi: "one" },
        { "id": 364, suomeksi: "kaksi", englanniksi: "two" },
        { "id": 365, suomeksi: "kolme", englanniksi: "three" },
        { "id": 366, suomeksi: "neljä", englanniksi: "four" },
        { "id": 367, suomeksi: "viisi", englanniksi: "five" },
        { "id": 368, suomeksi: "kuusi", englanniksi: "six" },
        { "id": 369, suomeksi: "seitsemän", englanniksi: "seven" },
        { "id": 370, suomeksi: "kahdeksan", englanniksi: "eight" },
        { "id": 371, suomeksi: "yhdeksän", englanniksi: "nine" },
        { "id": 372, suomeksi: "kymmenen", englanniksi: "ten" },
        { "id": 373, suomeksi: "yksitoista", englanniksi: "eleven" },
        { "id": 374, suomeksi: "kaksitoista", englanniksi: "twelve" },
        { "id": 375, suomeksi: "kolmetoista", englanniksi: "thirteen" },
        { "id": 376, suomeksi: "neljätoista", englanniksi: "fourteen" },
        { "id": 377, suomeksi: "viisitoista", englanniksi: "fifteen" },
        { "id": 378, suomeksi: "kuusitoista", englanniksi: "sixteen" },
        { "id": 379, suomeksi: "seitsemäntoista", englanniksi: "seventeen" },
        { "id": 380, suomeksi: "kahdeksantoista", englanniksi: "eighteen" },
        { "id": 381, suomeksi: "yhdeksäntoista", englanniksi: "nineteen" },
        { "id": 382, suomeksi: "kaksikymmentä", englanniksi: "twenty" },
        { "id": 383, suomeksi: "kaksikymmentäyksi", englanniksi: "twenty-one" },
        { "id": 895, suomeksi: "nolla", englanniksi: "zero" },
        { "id": 384, suomeksi: "kolmekymmentä", englanniksi: "thirty" },
        { "id": 385, suomeksi: "neljäkymmentä", englanniksi: "forty" },
        { "id": 386, suomeksi: "viisikymmentä", englanniksi: "fifty" },
        { "id": 387, suomeksi: "kuusikymmentä", englanniksi: "sixty" },
        { "id": 388, suomeksi: "seitsemänkymmentä", englanniksi: "seventy" },
        { "id": 389, suomeksi: "kahdeksankymmentä", englanniksi: "eighty" },
        { "id": 390, suomeksi: "yhdeksänkymmentä", englanniksi: "ninety" },
        { "id": 391, suomeksi: "sata", englanniksi: "hundred" },
        { "id": 392, suomeksi: "tuhat", englanniksi: "thousand" },
    ],
    "ordinal numbers": [
        { "id": 393, suomeksi: "ensimmäinen", englanniksi: "the first" },
        { "id": 394, suomeksi: "toinen", englanniksi: "the second" },
        { "id": 395, suomeksi: "kolmas", englanniksi: "the third" },
        { "id": 396, suomeksi: "neljäs", englanniksi: "the fourth" },
        { "id": 397, suomeksi: "viides", englanniksi: "the fifth" },
        { "id": 398, suomeksi: "kuudes", englanniksi: "the sixth" },
        { "id": 399, suomeksi: "seitsemäs", englanniksi: "the seventh" },
        { "id": 400, suomeksi: "kahdeksas", englanniksi: "the eighth" },
        { "id": 401, suomeksi: "yhdeksäs", englanniksi: "the ninth" },
        { "id": 402, suomeksi: "kymmenes", englanniksi: "the tenth" },
        { "id": 403, suomeksi: "yhdestoista", englanniksi: "the eleventh" },
        { "id": 404, suomeksi: "kahdestoista", englanniksi: "the twelfth" },
        { "id": 405, suomeksi: "kolmastoista", englanniksi: "the thirteenth" },
        { "id": 406, suomeksi: "neljästoista", englanniksi: "the fourteenth" },
        { "id": 407, suomeksi: "viidestoista", englanniksi: "the fifteenth" },
        { "id": 408, suomeksi: "kuudestoista", englanniksi: "the sixteenth" },
        { "id": 409, suomeksi: "seitsemästoista", englanniksi: "the seventeenth" },
        { "id": 410, suomeksi: "kahdeksastoista", englanniksi: "the eighteenth" },
        { "id": 411, suomeksi: "yhdeksästoista", englanniksi: "the nineteenth" },
        { "id": 412, suomeksi: "kahdeskymmenes", englanniksi: "the twentieth" },
        { "id": 413, suomeksi: "kahdeskymmenesensimmäinen", englanniksi: "the twenty-first" },
        { "id": 414, suomeksi: "kolmaskymmenes", englanniksi: "the thirtieth" },
        { "id": 415, suomeksi: "neljäskymmenes", englanniksi: "the fortieth" },
        { "id": 416, suomeksi: "viideskymmenes", englanniksi: "the fiftieth" },
        { "id": 417, suomeksi: "kuudeskymmenes", englanniksi: "the sixtieth" },
        { "id": 418, suomeksi: "seitsemäskymmenes", englanniksi: "the seventieth" },
        { "id": 419, suomeksi: "kahdeksaskymmenes", englanniksi: "the eightieth" },
        { "id": 420, suomeksi: "yhdeksäskymmenes", englanniksi: "the ninetieth" },
        { "id": 421, suomeksi: "sadas", englanniksi: "the hundredth" },
        { "id": 422, suomeksi: "tuhannes", englanniksi: "the thousandth" },
    ],
    "free time items": [
        { "id": 267, suomeksi: "kaiuttimet", englanniksi: "speakers" },
        { "id": 90, suomeksi: "puhelin", englanniksi: "phone" },
        { "id": 91, suomeksi: "kuulokkeet", englanniksi: "headphones" },
        { "id": 466, suomeksi: "taskulamppu", englanniksi: "flashlight" },
        { "id": 479, suomeksi: "pelikonsoli", englanniksi: "games console" },
        { "id": 481, suomeksi: "DVD-soitin", englanniksi: "DVD player" },
        { "id": 482, suomeksi: "CD-soitin", englanniksi: "CD player" },
        { "id": 483, suomeksi: "Blu-Ray soitin", englanniksi: "Blu-ray player" },
    ],
    "cleaning equipment": [
        { "id": 286, suomeksi: "pölynimuri", englanniksi: "vacuum cleaner" },
        { "id": 471, suomeksi: "moppi", englanniksi: "mop" },
        { "id": 467, suomeksi: "pesusieni", englanniksi: "sponge" },
        { "id": 478, suomeksi: "silitysrauta", englanniksi: "iron" },
        { "id": 480, suomeksi: "imuri", englanniksi: "vacuum cleaner" },
        { "id": 485, suomeksi: "luuta", englanniksi: "broom" },
        { "id": 486, suomeksi: "ämpäri", englanniksi: "bucket" },
    ],
    sports: [
        { "id": 848, suomeksi: "paini", englanniksi: "wrestling" },
        { "id": 849, suomeksi: "painonnosto", englanniksi: "weightlifting" },
        { "id": 850, suomeksi: "kävely", englanniksi: "walking" },
        { "id": 851, suomeksi: "lentopallo", englanniksi: "volleyball" },
        { "id": 852, suomeksi: "tennis", englanniksi: "tennis" },
        { "id": 853, suomeksi: "uinti", englanniksi: "swimming" },
        { "id": 854, suomeksi: "lumilautailu", englanniksi: "snowboarding" },
        { "id": 855, suomeksi: "hiihto", englanniksi: "skiing" },
        { "id": 856, suomeksi: "rullalautailu", englanniksi: "skateboarding" },
        { "id": 857, suomeksi: "laitesukellus", englanniksi: "scuba diving" },
        { "id": 858, suomeksi: "purjehdus", englanniksi: "sailing" },
        { "id": 859, suomeksi: "juoksu", englanniksi: "running" },
        { "id": 860, suomeksi: "soutu", englanniksi: "rowing" },
        { "id": 861, suomeksi: "vuorikiipeily", englanniksi: "mountain climbing" },
        { "id": 862, suomeksi: "moottoriurheilu", englanniksi: "motorsport" },
        { "id": 863, suomeksi: "karate", englanniksi: "karate" },
        { "id": 864, suomeksi: "judo", englanniksi: "judo" },
        { "id": 865, suomeksi: "lenkkeily", englanniksi: "jogging" },
        { "id": 866, suomeksi: "luistelu", englanniksi: "ice skating" },
        { "id": 867, suomeksi: "jääkiekko", englanniksi: "ice hockey" },
        { "id": 868, suomeksi: "ratsastus", englanniksi: "riding" },
        { "id": 869, suomeksi: "vaellus", englanniksi: "hiking" },
        { "id": 870, suomeksi: "käsipallo", englanniksi: "handball" },
        { "id": 871, suomeksi: "voimistelu", englanniksi: "gymnastics" },
        { "id": 872, suomeksi: "golf", englanniksi: "golf" },
        { "id": 873, suomeksi: "jalkapallo", englanniksi: "football" },
        { "id": 874, suomeksi: "kalastus", englanniksi: "fishing" },
        { "id": 875, suomeksi: "sukeltaminen", englanniksi: "diving" },
        { "id": 876, suomeksi: "pyöräily", englanniksi: "cycling" },
        { "id": 877, suomeksi: "kiipeily", englanniksi: "climbing" },
        { "id": 878, suomeksi: "melonta", englanniksi: "canoeing" },
        { "id": 879, suomeksi: "nyrkkeily", englanniksi: "boxing" },
        { "id": 880, suomeksi: "koripallo", englanniksi: "basketball" },
        { "id": 881, suomeksi: "sulkapallo", englanniksi: "badminton" },
        { "id": 882, suomeksi: "pesäpallo", englanniksi: "baseball" },
        { "id": 883, suomeksi: "yleisurheilu", englanniksi: "athletics" },
        { "id": 884, suomeksi: "amerikkalainen jalkapallo", englanniksi: "American football" },
    ],
    "holiday vocabulary": [
        { "id": 79, suomeksi: "hiusharja", englanniksi: "hair brush" },
        { "id": 594, suomeksi: "kamera", englanniksi: "camera" },
        { "id": 607, suomeksi: "meri", englanniksi: "sea" },
        { "id": 608, suomeksi: "aurinko", englanniksi: "sun" },
        { "id": 618, suomeksi: "snorklaus", englanniksi: "snorkeling" },
        { "id": 619, suomeksi: "turisti", englanniksi: "tourist" },
        { "id": 620, suomeksi: "lippu", englanniksi: "ticket" },
        { "id": 621, suomeksi: "passi", englanniksi: "passport" },
        { "id": 622, suomeksi: "muistoesine", englanniksi: "souvenir" },
        { "id": 623, suomeksi: "aurinkovoide", englanniksi: "sun lotion" },
        { "id": 624, suomeksi: "nähtävyyksien katselu", englanniksi: "sightseeing" },
        { "id": 625, suomeksi: "rentoutuminen", englanniksi: "relaxation" },
        { "id": 626, suomeksi: "matkustaminen", englanniksi: "travel" },
        { "id": 627, suomeksi: "kohde", englanniksi: "destination" },
        { "id": 628, suomeksi: "hotelli", englanniksi: "hotel" },
        { "id": 629, suomeksi: "lomakeskus", englanniksi: "resort" },
        { "id": 630, suomeksi: "aurinkolasit", englanniksi: "sunglasses" },
        { "id": 631, suomeksi: "pyyhe", englanniksi: "towel" },
        { "id": 633, suomeksi: "varvastossut", englanniksi: "flip-flops" },      
    ],
    "office supplies": [
        { "id": 73, suomeksi: "näyttö", englanniksi: "screen" },
        { "id": 74, suomeksi: "näppäimistö", englanniksi: "keyboard" },
        { "id": 75, suomeksi: "hiiri", englanniksi: "mouse" },
        { "id": 87, suomeksi: "laturi", englanniksi: "charger" },
        { "id": 88, suomeksi: "tietokone", englanniksi: "computer" },
        { "id": 89, suomeksi: "tabletti", englanniksi: "tablet" },
    ],
    sickness: [
        { "id": 597, suomeksi: "yskä", englanniksi: "cough" },
        { "id": 598, suomeksi: "flunssa", englanniksi: "cold" },
        { "id": 599, suomeksi: "kuume", englanniksi: "temperature" },
        { "id": 600, suomeksi: "vatsakipu", englanniksi: "tummy ache" },
        { "id": 601, suomeksi: "päänsärky", englanniksi: "headache" },
        { "id": 602, suomeksi: "hammassärky", englanniksi: "toothache" },
        { "id": 603, suomeksi: "korvasärky", englanniksi: "earache" },
        { "id": 604, suomeksi: "kurkkukipu", englanniksi: "sore throat" },
        { "id": 605, suomeksi: "murtunut jalka", englanniksi: "broken leg" },
    ],
    "school subjects": [
        { "id": 634, suomeksi: "kuvataide", englanniksi: "art" },
        { "id": 635, suomeksi: "biologia", englanniksi: "biology" },
        { "id": 636, suomeksi: "kemia", englanniksi: "chemistry" },
        { "id": 637, suomeksi: "käsityö", englanniksi: "crafts" },
        { "id": 638, suomeksi: "matematiikka", englanniksi: "maths" },
        { "id": 639, suomeksi: "musiikki", englanniksi: "music" },
        { "id": 640, suomeksi: "liikunta", englanniksi: "PE" },
        { "id": 641, suomeksi: "fysiikka", englanniksi: "physics" },
        { "id": 642, suomeksi: "historia", englanniksi: "history" },
        { "id": 643, suomeksi: "maantieto", englanniksi: "geography" },
    ],
};